#############################################################################
# Makefile for building: khopper
# Generated by qmake (2.01a) (Qt 4.5.1) on: Wed Jun 3 17:25:36 2009
# Project:  khopper.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -unix -o Makefile khopper.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-core \
		sub-main \
		sub-plugins

core//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) core/ || $(MKDIR) core/ 
	cd core/ && $(QMAKE) core.pro -unix -o $(MAKEFILE)
sub-core-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) core/ || $(MKDIR) core/ 
	cd core/ && $(QMAKE) core.pro -unix -o $(MAKEFILE)
sub-core: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE)
sub-core-make_default-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) 
sub-core-make_default: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) 
sub-core-make_first-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) first
sub-core-make_first: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) first
sub-core-all-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) all
sub-core-all: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) all
sub-core-clean-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) clean
sub-core-clean: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) clean
sub-core-distclean-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) distclean
sub-core-distclean: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) distclean
sub-core-install_subtargets-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) install
sub-core-install_subtargets: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) install
sub-core-uninstall_subtargets-ordered: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-core-uninstall_subtargets: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) uninstall
main//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) main/ || $(MKDIR) main/ 
	cd main/ && $(QMAKE) main.pro -unix -o $(MAKEFILE)
sub-main-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) main/ || $(MKDIR) main/ 
	cd main/ && $(QMAKE) main.pro -unix -o $(MAKEFILE)
sub-main: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE)
sub-main-make_default-ordered: main//$(MAKEFILE) sub-core-make_default-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) 
sub-main-make_default: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) 
sub-main-make_first-ordered: main//$(MAKEFILE) sub-core-make_first-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) first
sub-main-make_first: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) first
sub-main-all-ordered: main//$(MAKEFILE) sub-core-all-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) all
sub-main-all: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) all
sub-main-clean-ordered: main//$(MAKEFILE) sub-core-clean-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) clean
sub-main-clean: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) clean
sub-main-distclean-ordered: main//$(MAKEFILE) sub-core-distclean-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) distclean
sub-main-distclean: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) distclean
sub-main-install_subtargets-ordered: main//$(MAKEFILE) sub-core-install_subtargets-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) install
sub-main-install_subtargets: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) install
sub-main-uninstall_subtargets-ordered: main//$(MAKEFILE) sub-core-uninstall_subtargets-ordered  FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-main-uninstall_subtargets: main//$(MAKEFILE) FORCE
	cd main/ && $(MAKE) -f $(MAKEFILE) uninstall
plugins//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) plugins.pro -unix -o $(MAKEFILE)
sub-plugins-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) plugins.pro -unix -o $(MAKEFILE)
sub-plugins: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE)
sub-plugins-make_default-ordered: plugins//$(MAKEFILE) sub-main-make_default-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-make_default: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-make_first-ordered: plugins//$(MAKEFILE) sub-main-make_first-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-make_first: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-all-ordered: plugins//$(MAKEFILE) sub-main-all-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-all: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-clean-ordered: plugins//$(MAKEFILE) sub-main-clean-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-clean: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-distclean-ordered: plugins//$(MAKEFILE) sub-main-distclean-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-distclean: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-install_subtargets-ordered: plugins//$(MAKEFILE) sub-main-install_subtargets-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-install_subtargets: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-uninstall_subtargets-ordered: plugins//$(MAKEFILE) sub-main-uninstall_subtargets-ordered  FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-plugins-uninstall_subtargets: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: khopper.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/debug_and_release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile khopper.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/debug_and_release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile khopper.pro

qmake_all: sub-core-qmake_all sub-main-qmake_all sub-plugins-qmake_all FORCE

make_default: sub-core-make_default-ordered sub-main-make_default-ordered sub-plugins-make_default-ordered FORCE
make_first: sub-core-make_first-ordered sub-main-make_first-ordered sub-plugins-make_first-ordered FORCE
all: sub-core-all-ordered sub-main-all-ordered sub-plugins-all-ordered FORCE
clean: sub-core-clean-ordered sub-main-clean-ordered sub-plugins-clean-ordered FORCE
distclean: sub-core-distclean-ordered sub-main-distclean-ordered sub-plugins-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-core-install_subtargets-ordered sub-main-install_subtargets-ordered sub-plugins-install_subtargets-ordered FORCE
uninstall_subtargets: sub-core-uninstall_subtargets-ordered sub-main-uninstall_subtargets-ordered sub-plugins-uninstall_subtargets-ordered FORCE

sub-core-sub_Debug_ordered: core/$(MAKEFILE)
	cd core/ && $(MAKE) debug
sub-main-sub_Debug_ordered: main/$(MAKEFILE) sub-core-sub_Debug_ordered 
	cd main/ && $(MAKE) debug
sub-plugins-sub_Debug_ordered: plugins/$(MAKEFILE) sub-main-sub_Debug_ordered 
	cd plugins/ && $(MAKE) debug
debug: sub-core-sub_Debug_ordered sub-main-sub_Debug_ordered sub-plugins-sub_Debug_ordered

sub-core-sub_Release_ordered: core/$(MAKEFILE)
	cd core/ && $(MAKE) release
sub-main-sub_Release_ordered: main/$(MAKEFILE) sub-core-sub_Release_ordered 
	cd main/ && $(MAKE) release
sub-plugins-sub_Release_ordered: plugins/$(MAKEFILE) sub-main-sub_Release_ordered 
	cd plugins/ && $(MAKE) release
release: sub-core-sub_Release_ordered sub-main-sub_Release_ordered sub-plugins-sub_Release_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

